### ISSUE TITLE
Boeing 748 Intercontinental Support

### ISSUE THREAD

**Issue by DemonRem** [haversine-air/AirPlugin#13]
Dear Haversine-air Team,

I wonder if you can add support to this aircraft

his name is : SSG 747-800 this is the aircraft model

**Comment by jonvcb** [comment]
Hello, 

For which app? I think it was somehow compatible as it was based with AirFMC as its FMC is based on the FJCC as far as I remember. There are some limitations with AirTrack due to accessing the flight plan not  being possible. 

Let me know which and I can see what can be done. 

thanks,
joao

**Comment by DemonRem** [comment]
we speak on AirFMC

**Comment by jonvcb** [comment]
Just tired with 747 v1.7 and it seems to work fine. 

It configures by checking for the presence of the "SSG/UFMC/PRESENT" dataref. See: https://github.com/haversine-air/AirPlugin/blob/master/source/hsxplufmc.c

Which version are you running? What happens when you connect?

I just put a small fix which you can try by getting the latest binary plugin which I just uploaded from: 

https://github.com/haversine-air/AirPlugin/tree/master/HaversineAir

it will report as: 4.7.9a

hope it helps, 
joao

**Comment by DemonRem** [comment]
work now :)

thank
